#pragma once

#define WCLAP_MULTIPLE_INCLUDES_NAMESPACE wclap32
#define WCLAP_MULTIPLE_INCLUDES_WASMP uint32_t
#include "../wclapN/wclap-arenas.h"
#undef WCLAP_MULTIPLE_INCLUDES_NAMESPACE
#undef WCLAP_MULTIPLE_INCLUDES_WASMP

