/* Generated by translate-clap-structs.js */
namespace wclap { namespace wclap64 {

using WasmP = uint64_t;

using wclap_version = clap_version_t;

struct wclap_process {
	wclap_process(unsigned char * pointerInWasm) : pointerInWasm(pointerInWasm) {}
	
	operator bool() const {
		return pointerInWasm;
	}

	int64_t & steady_time() {
		return *(int64_t *)pointerInWasm;
	}
	uint32_t & frames_count() {
		return *(uint32_t *)(pointerInWasm + 8);
	}
	WasmP & transport() {
		return *(WasmP *)(pointerInWasm + 16);
	}
	WasmP & audio_inputs() {
		return *(WasmP *)(pointerInWasm + 24);
	}
	WasmP & audio_outputs() {
		return *(WasmP *)(pointerInWasm + 32);
	}
	uint32_t & audio_inputs_count() {
		return *(uint32_t *)(pointerInWasm + 36);
	}
	uint32_t & audio_outputs_count() {
		return *(uint32_t *)(pointerInWasm + 40);
	}
	WasmP & in_events() {
		return *(WasmP *)(pointerInWasm + 48);
	}
	WasmP & out_events() {
		return *(WasmP *)(pointerInWasm + 56);
	}
private:
	unsigned char * pointerInWasm;
};

struct wclap_plugin_descriptor {
	wclap_plugin_descriptor(unsigned char * pointerInWasm) : pointerInWasm(pointerInWasm) {}
	
	operator bool() const {
		return pointerInWasm;
	}

	clap_version_t & clap_version() {
		return *(clap_version_t *)pointerInWasm;
	}
	WasmP & id() {
		return *(WasmP *)(pointerInWasm + 16);
	}
	WasmP & name() {
		return *(WasmP *)(pointerInWasm + 24);
	}
	WasmP & vendor() {
		return *(WasmP *)(pointerInWasm + 32);
	}
	WasmP & url() {
		return *(WasmP *)(pointerInWasm + 40);
	}
	WasmP & manual_url() {
		return *(WasmP *)(pointerInWasm + 48);
	}
	WasmP & support_url() {
		return *(WasmP *)(pointerInWasm + 56);
	}
	WasmP & version() {
		return *(WasmP *)(pointerInWasm + 64);
	}
	WasmP & description() {
		return *(WasmP *)(pointerInWasm + 72);
	}
	WasmP & features() {
		return *(WasmP *)(pointerInWasm + 80);
	}
private:
	unsigned char * pointerInWasm;
};

struct wclap_plugin {
	wclap_plugin(unsigned char * pointerInWasm) : pointerInWasm(pointerInWasm) {}
	
	operator bool() const {
		return pointerInWasm;
	}

	WasmP & desc() {
		return *(WasmP *)pointerInWasm;
	}
	WasmP & plugin_data() {
		return *(WasmP *)(pointerInWasm + 8);
	}
	WasmP & init() {
		return *(WasmP *)(pointerInWasm + 16);
	}
	WasmP & destroy() {
		return *(WasmP *)(pointerInWasm + 24);
	}
	WasmP & activate() {
		return *(WasmP *)(pointerInWasm + 32);
	}
	WasmP & deactivate() {
		return *(WasmP *)(pointerInWasm + 40);
	}
	WasmP & start_processing() {
		return *(WasmP *)(pointerInWasm + 48);
	}
	WasmP & stop_processing() {
		return *(WasmP *)(pointerInWasm + 56);
	}
	WasmP & reset() {
		return *(WasmP *)(pointerInWasm + 64);
	}
	WasmP & process() {
		return *(WasmP *)(pointerInWasm + 72);
	}
	WasmP & get_extension() {
		return *(WasmP *)(pointerInWasm + 80);
	}
	WasmP & on_main_thread() {
		return *(WasmP *)(pointerInWasm + 88);
	}
private:
	unsigned char * pointerInWasm;
};

struct wclap_plugin_factory {
	wclap_plugin_factory(unsigned char * pointerInWasm) : pointerInWasm(pointerInWasm) {}
	
	operator bool() const {
		return pointerInWasm;
	}

	WasmP & get_plugin_count() {
		return *(WasmP *)pointerInWasm;
	}
	WasmP & get_plugin_descriptor() {
		return *(WasmP *)(pointerInWasm + 8);
	}
	WasmP & create_plugin() {
		return *(WasmP *)(pointerInWasm + 16);
	}
private:
	unsigned char * pointerInWasm;
};

struct wclap_plugin_entry {
	wclap_plugin_entry(unsigned char * pointerInWasm) : pointerInWasm(pointerInWasm) {}
	
	operator bool() const {
		return pointerInWasm;
	}

	clap_version_t & clap_version() {
		return *(clap_version_t *)pointerInWasm;
	}
	WasmP & init() {
		return *(WasmP *)(pointerInWasm + 16);
	}
	WasmP & deinit() {
		return *(WasmP *)(pointerInWasm + 24);
	}
	WasmP & get_factory() {
		return *(WasmP *)(pointerInWasm + 32);
	}
private:
	unsigned char * pointerInWasm;
};
}} // namespace
