/* Generated by translate-clap-structs.js */

template<>
struct Wclap64TranslateStruct<clap_plugin_entry_t> {
	using WasmP = uint64_t;
	// translate all the fields
	static void assignWasmToNative(WclapTranslationScope<true> *translate, WasmP wasmP, clap_plugin_entry_t &native) {
		translate->assignWasmToNativeDirect<clap_version_t>(wasmP, native.clap_version);
		translate->assignWasmToNative_IL(wasmP + 16, native.init); // bool init(const char *)
		translate->assignWasmToNative_v(wasmP + 24, native.deinit); // void deinit()
		translate->assignWasmToNative_LL(wasmP + 32, native.get_factory); // const void * get_factory(const char *)
	}
	// translate all the fields
	static void assignNativeToWasm(WclapTranslationScope<true> *translate, clap_plugin_entry_t const &native, WasmP wasmP) {
		translate->assignNativeToWasmDirect<clap_version_t>(native.clap_version, wasmP);
		translate->assignNativeToWasm_IL(native.init, wasmP + 16); // bool init(const char *)
		translate->assignNativeToWasm_v(native.deinit, wasmP + 24); // void deinit()
		translate->assignNativeToWasm_LL(native.get_factory, wasmP + 32); // const void * get_factory(const char *)
	}
};
template<>
struct Wclap64TranslateStruct<clap_plugin_descriptor_t> {
	using WasmP = uint64_t;
	// translate all the fields
	static void assignWasmToNative(WclapTranslationScope<true> *translate, WasmP wasmP, clap_plugin_descriptor_t &native) {
		translate->assignWasmToNativeDirect<clap_version_t>(wasmP, native.clap_version);
		translate->assignWasmToNative<const char *>(wasmP + 16, native.id);
		translate->assignWasmToNative<const char *>(wasmP + 16, native.name);
		translate->assignWasmToNative<const char *>(wasmP + 16, native.vendor);
		translate->assignWasmToNative<const char *>(wasmP + 16, native.url);
		translate->assignWasmToNative<const char *>(wasmP + 16, native.manual_url);
		translate->assignWasmToNative<const char *>(wasmP + 16, native.support_url);
		translate->assignWasmToNative<const char *>(wasmP + 16, native.version);
		translate->assignWasmToNative<const char *>(wasmP + 16, native.description);
		translate->assignWasmToNative_clap_plugin_descriptor_t_features(wasmP + 16, native.features);
	}
	// translate all the fields
	static void assignNativeToWasm(WclapTranslationScope<true> *translate, clap_plugin_descriptor_t const &native, WasmP wasmP) {
		translate->assignNativeToWasmDirect<clap_version_t>(native.clap_version, wasmP);
		translate->assignNativeToWasm<const char *>(native.id, wasmP + 16);
		translate->assignNativeToWasm<const char *>(native.name, wasmP + 16);
		translate->assignNativeToWasm<const char *>(native.vendor, wasmP + 16);
		translate->assignNativeToWasm<const char *>(native.url, wasmP + 16);
		translate->assignNativeToWasm<const char *>(native.manual_url, wasmP + 16);
		translate->assignNativeToWasm<const char *>(native.support_url, wasmP + 16);
		translate->assignNativeToWasm<const char *>(native.version, wasmP + 16);
		translate->assignNativeToWasm<const char *>(native.description, wasmP + 16);
		translate->assignNativeToWasm_clap_plugin_descriptor_t_features(native.features, wasmP + 16);
	}
};
template<>
struct Wclap64TranslateStruct<clap_plugin_factory_t> {
	using WasmP = uint64_t;
	// translate all the fields
	static void assignWasmToNative(WclapTranslationScope<true> *translate, WasmP wasmP, clap_plugin_factory_t &native) {
		translate->assignWasmToNative_IL(wasmP, native.get_plugin_count); // uint32_t get_plugin_count(clap_plugin_factory_t *)
		translate->assignWasmToNative_LLI(wasmP + 8, native.get_plugin_descriptor); // clap_plugin_descriptor_t * get_plugin_descriptor(clap_plugin_factory_t *,uint32_t)
		translate->assignWasmToNative_LLLL(wasmP + 16, native.create_plugin); // clap_plugin_t * create_plugin(clap_plugin_factory_t *,clap_host_t *,const char *)
	}
	// translate all the fields
	static void assignNativeToWasm(WclapTranslationScope<true> *translate, clap_plugin_factory_t const &native, WasmP wasmP) {
		translate->assignNativeToWasm_IL(native.get_plugin_count, wasmP); // uint32_t get_plugin_count(clap_plugin_factory_t *)
		translate->assignNativeToWasm_LLI(native.get_plugin_descriptor, wasmP + 8); // clap_plugin_descriptor_t * get_plugin_descriptor(clap_plugin_factory_t *,uint32_t)
		translate->assignNativeToWasm_LLLL(native.create_plugin, wasmP + 16); // clap_plugin_t * create_plugin(clap_plugin_factory_t *,clap_host_t *,const char *)
	}
};