/* Generated by translate-clap-structs.js */

template<>
struct Wclap32TranslateStruct<clap_plugin_descriptor_t> {
	using WasmP = uint32_t;
	static void assignWasmToNative(WclapTranslationScope<false> *translate, WasmP wasmP, clap_plugin_descriptor_t &native) {
		translate->assignWasmToNativeDirect<clap_version_t>(wasmP, native.clap_version);
		translate->assignWasmToNative<const char *>(wasmP + 12, native.id);
		translate->assignWasmToNative<const char *>(wasmP + 12, native.name);
		translate->assignWasmToNative<const char *>(wasmP + 12, native.vendor);
		translate->assignWasmToNative<const char *>(wasmP + 12, native.url);
		translate->assignWasmToNative<const char *>(wasmP + 12, native.manual_url);
		translate->assignWasmToNative<const char *>(wasmP + 12, native.support_url);
		translate->assignWasmToNative<const char *>(wasmP + 12, native.version);
		translate->assignWasmToNative<const char *>(wasmP + 12, native.description);
		translate->assignWasmToNative_clap_plugin_descriptor_t_features(wasmP + 12, native.features);
	}
	static void assignNativeToWasm(WclapTranslationScope<false> *translate, clap_plugin_descriptor_t const &native, WasmP wasmP) {
		translate->assignNativeToWasmDirect<clap_version_t>(native.clap_version, wasmP);
		translate->assignNativeToWasm<const char *>(native.id, wasmP + 12);
		translate->assignNativeToWasm<const char *>(native.name, wasmP + 12);
		translate->assignNativeToWasm<const char *>(native.vendor, wasmP + 12);
		translate->assignNativeToWasm<const char *>(native.url, wasmP + 12);
		translate->assignNativeToWasm<const char *>(native.manual_url, wasmP + 12);
		translate->assignNativeToWasm<const char *>(native.support_url, wasmP + 12);
		translate->assignNativeToWasm<const char *>(native.version, wasmP + 12);
		translate->assignNativeToWasm<const char *>(native.description, wasmP + 12);
		translate->assignNativeToWasm_clap_plugin_descriptor_t_features(native.features, wasmP + 12);
	}
};
template<>
struct Wclap32TranslateStruct<clap_plugin_factory_t> {
	using WasmP = uint32_t;
	static void assignWasmToNative(WclapTranslationScope<false> *translate, WasmP wasmP, WclapLifetimeStruct<clap_plugin_factory_t> &native) {
		native.get_plugin_count = callWasmFromNative_get_plugin_count;
		native.get_plugin_descriptor = callWasmFromNative_get_plugin_descriptor;
		native.create_plugin = callWasmFromNative_create_plugin;
	}
	static void assignNativeToWasm(WclapTranslationScope<false> *translate, clap_plugin_factory_t const &native, WasmP wasmP) {
		*(WasmP *)wasmP = translate.wasmMethods.clap_plugin_factory_t.get_plugin_count; // uint32_t get_plugin_count(clap_plugin_factory_t *)
		*(WasmP *)wasmP + 4 = translate.wasmMethods.clap_plugin_factory_t.get_plugin_descriptor; // clap_plugin_descriptor_t * get_plugin_descriptor(clap_plugin_factory_t *,uint32_t)
		*(WasmP *)wasmP + 8 = translate.wasmMethods.clap_plugin_factory_t.create_plugin; // clap_plugin_t * create_plugin(clap_plugin_factory_t *,clap_host_t *,const char *)
	}

	// method proxies
	uint32_t callWasmFromNative_get_plugin_count(clap_plugin_factory_t *arg0) {
		beep boop
		auto *obj0 = (WclapLifetimeStruct<clap_plugin_factory_t> *)arg0;
		auto *context = (WclapTranslationScope<false> *)obj0->wclapTranslationScope;
	}
	clap_plugin_descriptor_t * callWasmFromNative_get_plugin_descriptor(clap_plugin_factory_t *arg0, uint32_t arg1) {
		beep boop
		auto *obj0 = (WclapLifetimeStruct<clap_plugin_factory_t> *)arg0;
		auto *context = (WclapTranslationScope<false> *)obj0->wclapTranslationScope;
	}
	clap_plugin_t * callWasmFromNative_create_plugin(clap_plugin_factory_t *arg0, clap_host_t *arg1, const char *arg2) {
		beep boop
		auto *obj0 = (WclapLifetimeStruct<clap_plugin_factory_t> *)arg0;
		auto *context = (WclapTranslationScope<false> *)obj0->wclapTranslationScope;
	}
};

template<>
struct WclapTranslator<false> {
	Wclap32TranslateStruct<clap_window_t> clap_window_t;
	Wclap32TranslateStruct<clap_host_t> clap_host_t;
	Wclap32TranslateStruct<clap_plugin_t> clap_plugin_t;
	Wclap32TranslateStruct<clap_plugin_descriptor_t> clap_plugin_descriptor_t;
	Wclap32TranslateStruct<clap_plugin_factory_t> clap_plugin_factory_t;
	
	template<class Fn>
	void mapMethods(Fn &&fn) {
		clap_window_t.mapMethods(fn);
		clap_host_t.mapMethods(fn);
		clap_plugin_t.mapMethods(fn);
		clap_plugin_descriptor_t.mapMethods(fn);
		clap_plugin_factory_t.mapMethods(fn);
	}
};
	