/* Generated by translate-clap-structs.js */
namespace wclap { namespace wclap32 {

using WasmP = uint32_t;

using Wclap_clap_version_t = clap_version_t;

class Wclap_clap_process_t {
	unsigned char *pointerInWasm;
	WclapTranslationScope &translationScope;
public:
	Wclap_clap_process_t(unsigned char *p, WclapTranslationScope &scope) : pointerInWasm(p), translationScope(scope) {}
	
	int64_t & steady_time() {
		return *(int64_t *)pointerInWasm;
	}
	uint32_t & frames_count() {
		return *(uint32_t *)(pointerInWasm + 8);
	}
	WasmP & transport() {
		return *(WasmP *)(pointerInWasm + 12);
	}
	WasmP & audio_inputs() {
		return *(WasmP *)(pointerInWasm + 16);
	}
	WasmP & audio_outputs() {
		return *(WasmP *)(pointerInWasm + 20);
	}
	uint32_t & audio_inputs_count() {
		return *(uint32_t *)(pointerInWasm + 24);
	}
	uint32_t & audio_outputs_count() {
		return *(uint32_t *)(pointerInWasm + 28);
	}
	WasmP & in_events() {
		return *(WasmP *)(pointerInWasm + 32);
	}
	WasmP & out_events() {
		return *(WasmP *)(pointerInWasm + 36);
	}
};

class Wclap_clap_plugin_descriptor_t {
	unsigned char *pointerInWasm;
	WclapTranslationScope &translationScope;
public:
	Wclap_clap_plugin_descriptor_t(unsigned char *p, WclapTranslationScope &scope) : pointerInWasm(p), translationScope(scope) {}
	
	clap_version_t & clap_version() {
		return *(clap_version_t *)pointerInWasm;
	}
	WasmP & id() {
		return *(WasmP *)(pointerInWasm + 12);
	}
	WasmP & name() {
		return *(WasmP *)(pointerInWasm + 16);
	}
	WasmP & vendor() {
		return *(WasmP *)(pointerInWasm + 20);
	}
	WasmP & url() {
		return *(WasmP *)(pointerInWasm + 24);
	}
	WasmP & manual_url() {
		return *(WasmP *)(pointerInWasm + 28);
	}
	WasmP & support_url() {
		return *(WasmP *)(pointerInWasm + 32);
	}
	WasmP & version() {
		return *(WasmP *)(pointerInWasm + 36);
	}
	WasmP & description() {
		return *(WasmP *)(pointerInWasm + 40);
	}
	WasmP & features() {
		return *(WasmP *)(pointerInWasm + 44);
	}
};

class Wclap_clap_plugin_t {
	unsigned char *pointerInWasm;
	WclapTranslationScope &translationScope;
public:
	Wclap_clap_plugin_t(unsigned char *p, WclapTranslationScope &scope) : pointerInWasm(p), translationScope(scope) {}
	
	WasmP & desc() {
		return *(WasmP *)pointerInWasm;
	}
	WasmP & plugin_data() {
		return *(WasmP *)(pointerInWasm + 4);
	}
	WasmP & init() {
		return *(WasmP *)(pointerInWasm + 8);
	}
	WasmP & destroy() {
		return *(WasmP *)(pointerInWasm + 12);
	}
	WasmP & activate() {
		return *(WasmP *)(pointerInWasm + 16);
	}
	WasmP & deactivate() {
		return *(WasmP *)(pointerInWasm + 20);
	}
	WasmP & start_processing() {
		return *(WasmP *)(pointerInWasm + 24);
	}
	WasmP & stop_processing() {
		return *(WasmP *)(pointerInWasm + 28);
	}
	WasmP & reset() {
		return *(WasmP *)(pointerInWasm + 32);
	}
	WasmP & process() {
		return *(WasmP *)(pointerInWasm + 36);
	}
	WasmP & get_extension() {
		return *(WasmP *)(pointerInWasm + 40);
	}
	WasmP & on_main_thread() {
		return *(WasmP *)(pointerInWasm + 44);
	}
};

class Wclap_clap_plugin_factory_t {
	unsigned char *pointerInWasm;
	WclapTranslationScope &translationScope;
public:
	Wclap_clap_plugin_factory_t(unsigned char *p, WclapTranslationScope &scope) : pointerInWasm(p), translationScope(scope) {}
	
	WasmP & get_plugin_count() {
		return *(WasmP *)pointerInWasm;
	}
	WasmP & get_plugin_descriptor() {
		return *(WasmP *)(pointerInWasm + 4);
	}
	WasmP & create_plugin() {
		return *(WasmP *)(pointerInWasm + 8);
	}
};

class Wclap_clap_plugin_entry_t {
	unsigned char *pointerInWasm;
	WclapTranslationScope &translationScope;
public:
	Wclap_clap_plugin_entry_t(unsigned char *p, WclapTranslationScope &scope) : pointerInWasm(p), translationScope(scope) {}
	
	clap_version_t & clap_version() {
		return *(clap_version_t *)pointerInWasm;
	}
	WasmP & init() {
		return *(WasmP *)(pointerInWasm + 12);
	}
	WasmP & deinit() {
		return *(WasmP *)(pointerInWasm + 16);
	}
	WasmP & get_factory() {
		return *(WasmP *)(pointerInWasm + 20);
	}
};
}} // namespace
